### ISSUE TITLE
Get all team members video footage or audio recording for Mission's video.

### ISSUE THREAD

**Issue by shafeeshafee** [shafeeshafee/tsundoku#63]
### Send Shafee--via slack or discord--a recording for our Mission video.

- 20-40 seconds
- Answers a question
- Interview angle (looking semi-sideways, not directly at camera)
- Be authentically ***you***

It would be efficient if we can get this out of the way as fast as possible, since editing and perfecting videos takes a while on Premiere.

![QssSdxr](https://user-images.githubusercontent.com/68356865/111493301-cee25580-8713-11eb-81ff-cdcca011db99.png)

**Comment by blaquebeardcoder** [comment]
![option1](https://user-images.githubusercontent.com/68349525/111508183-cbee6180-8721-11eb-99be-801f62e79378.JPG)
Video file is too large-- sent via Slack.
